# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: swarnim 
  CLOUD_SQL_PASSWORD: 1234
  CLOUD_SQL_DATABASE_NAME: Demo
  CLOUD_SQL_CONNECTION_NAME: eng-scene-273903:us-central1:cloud-proj
  CLOUD_STORAGE_BUCKET: cc-2
handlers:
- url: /template
  static_dir: template
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 50
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50 
