//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsSOAPClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name strng from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vowels", ReplyAction="*")]
        WindowsSOAPClient.ServiceReference1.vowelsResponse vowels(WindowsSOAPClient.ServiceReference1.vowelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/vowels", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.vowelsResponse> vowelsAsync(WindowsSOAPClient.ServiceReference1.vowelsRequest request);
        
        // CODEGEN: Generating message contract since element name strng from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uppercase", ReplyAction="*")]
        WindowsSOAPClient.ServiceReference1.uppercaseResponse uppercase(WindowsSOAPClient.ServiceReference1.uppercaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uppercase", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.uppercaseResponse> uppercaseAsync(WindowsSOAPClient.ServiceReference1.uppercaseRequest request);
        
        // CODEGEN: Generating message contract since element name strng from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reverse", ReplyAction="*")]
        WindowsSOAPClient.ServiceReference1.reverseResponse reverse(WindowsSOAPClient.ServiceReference1.reverseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reverse", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.reverseResponse> reverseAsync(WindowsSOAPClient.ServiceReference1.reverseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vowelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vowels", Namespace="http://tempuri.org/", Order=0)]
        public WindowsSOAPClient.ServiceReference1.vowelsRequestBody Body;
        
        public vowelsRequest() {
        }
        
        public vowelsRequest(WindowsSOAPClient.ServiceReference1.vowelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vowelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strng;
        
        public vowelsRequestBody() {
        }
        
        public vowelsRequestBody(string strng) {
            this.strng = strng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vowelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="vowelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsSOAPClient.ServiceReference1.vowelsResponseBody Body;
        
        public vowelsResponse() {
        }
        
        public vowelsResponse(WindowsSOAPClient.ServiceReference1.vowelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class vowelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int vowelsResult;
        
        public vowelsResponseBody() {
        }
        
        public vowelsResponseBody(int vowelsResult) {
            this.vowelsResult = vowelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uppercaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uppercase", Namespace="http://tempuri.org/", Order=0)]
        public WindowsSOAPClient.ServiceReference1.uppercaseRequestBody Body;
        
        public uppercaseRequest() {
        }
        
        public uppercaseRequest(WindowsSOAPClient.ServiceReference1.uppercaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uppercaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strng;
        
        public uppercaseRequestBody() {
        }
        
        public uppercaseRequestBody(string strng) {
            this.strng = strng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uppercaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uppercaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsSOAPClient.ServiceReference1.uppercaseResponseBody Body;
        
        public uppercaseResponse() {
        }
        
        public uppercaseResponse(WindowsSOAPClient.ServiceReference1.uppercaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class uppercaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int uppercaseResult;
        
        public uppercaseResponseBody() {
        }
        
        public uppercaseResponseBody(int uppercaseResult) {
            this.uppercaseResult = uppercaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reverseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reverse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsSOAPClient.ServiceReference1.reverseRequestBody Body;
        
        public reverseRequest() {
        }
        
        public reverseRequest(WindowsSOAPClient.ServiceReference1.reverseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reverseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strng;
        
        public reverseRequestBody() {
        }
        
        public reverseRequestBody(string strng) {
            this.strng = strng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reverseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reverseResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsSOAPClient.ServiceReference1.reverseResponseBody Body;
        
        public reverseResponse() {
        }
        
        public reverseResponse(WindowsSOAPClient.ServiceReference1.reverseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reverseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reverseResult;
        
        public reverseResponseBody() {
        }
        
        public reverseResponseBody(string reverseResult) {
            this.reverseResult = reverseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsSOAPClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsSOAPClient.ServiceReference1.WebService1Soap>, WindowsSOAPClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsSOAPClient.ServiceReference1.vowelsResponse WindowsSOAPClient.ServiceReference1.WebService1Soap.vowels(WindowsSOAPClient.ServiceReference1.vowelsRequest request) {
            return base.Channel.vowels(request);
        }
        
        public int vowels(string strng) {
            WindowsSOAPClient.ServiceReference1.vowelsRequest inValue = new WindowsSOAPClient.ServiceReference1.vowelsRequest();
            inValue.Body = new WindowsSOAPClient.ServiceReference1.vowelsRequestBody();
            inValue.Body.strng = strng;
            WindowsSOAPClient.ServiceReference1.vowelsResponse retVal = ((WindowsSOAPClient.ServiceReference1.WebService1Soap)(this)).vowels(inValue);
            return retVal.Body.vowelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.vowelsResponse> WindowsSOAPClient.ServiceReference1.WebService1Soap.vowelsAsync(WindowsSOAPClient.ServiceReference1.vowelsRequest request) {
            return base.Channel.vowelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.vowelsResponse> vowelsAsync(string strng) {
            WindowsSOAPClient.ServiceReference1.vowelsRequest inValue = new WindowsSOAPClient.ServiceReference1.vowelsRequest();
            inValue.Body = new WindowsSOAPClient.ServiceReference1.vowelsRequestBody();
            inValue.Body.strng = strng;
            return ((WindowsSOAPClient.ServiceReference1.WebService1Soap)(this)).vowelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsSOAPClient.ServiceReference1.uppercaseResponse WindowsSOAPClient.ServiceReference1.WebService1Soap.uppercase(WindowsSOAPClient.ServiceReference1.uppercaseRequest request) {
            return base.Channel.uppercase(request);
        }
        
        public int uppercase(string strng) {
            WindowsSOAPClient.ServiceReference1.uppercaseRequest inValue = new WindowsSOAPClient.ServiceReference1.uppercaseRequest();
            inValue.Body = new WindowsSOAPClient.ServiceReference1.uppercaseRequestBody();
            inValue.Body.strng = strng;
            WindowsSOAPClient.ServiceReference1.uppercaseResponse retVal = ((WindowsSOAPClient.ServiceReference1.WebService1Soap)(this)).uppercase(inValue);
            return retVal.Body.uppercaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.uppercaseResponse> WindowsSOAPClient.ServiceReference1.WebService1Soap.uppercaseAsync(WindowsSOAPClient.ServiceReference1.uppercaseRequest request) {
            return base.Channel.uppercaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.uppercaseResponse> uppercaseAsync(string strng) {
            WindowsSOAPClient.ServiceReference1.uppercaseRequest inValue = new WindowsSOAPClient.ServiceReference1.uppercaseRequest();
            inValue.Body = new WindowsSOAPClient.ServiceReference1.uppercaseRequestBody();
            inValue.Body.strng = strng;
            return ((WindowsSOAPClient.ServiceReference1.WebService1Soap)(this)).uppercaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsSOAPClient.ServiceReference1.reverseResponse WindowsSOAPClient.ServiceReference1.WebService1Soap.reverse(WindowsSOAPClient.ServiceReference1.reverseRequest request) {
            return base.Channel.reverse(request);
        }
        
        public string reverse(string strng) {
            WindowsSOAPClient.ServiceReference1.reverseRequest inValue = new WindowsSOAPClient.ServiceReference1.reverseRequest();
            inValue.Body = new WindowsSOAPClient.ServiceReference1.reverseRequestBody();
            inValue.Body.strng = strng;
            WindowsSOAPClient.ServiceReference1.reverseResponse retVal = ((WindowsSOAPClient.ServiceReference1.WebService1Soap)(this)).reverse(inValue);
            return retVal.Body.reverseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.reverseResponse> WindowsSOAPClient.ServiceReference1.WebService1Soap.reverseAsync(WindowsSOAPClient.ServiceReference1.reverseRequest request) {
            return base.Channel.reverseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsSOAPClient.ServiceReference1.reverseResponse> reverseAsync(string strng) {
            WindowsSOAPClient.ServiceReference1.reverseRequest inValue = new WindowsSOAPClient.ServiceReference1.reverseRequest();
            inValue.Body = new WindowsSOAPClient.ServiceReference1.reverseRequestBody();
            inValue.Body.strng = strng;
            return ((WindowsSOAPClient.ServiceReference1.WebService1Soap)(this)).reverseAsync(inValue);
        }
    }
}
